/**
 * CDR Cognee Indexer — Static Banking Knowledge Documents
 *
 * Expert-curated banking knowledge documents for the Cognee knowledge graph.
 * These cover Australian lending, deposits, CDR categories, and more.
 */

export const BANKING_KNOWLEDGE_DOCS: string[] = [
  `Australian Lending Rate Types: Variable rates track the lender's standard variable rate (SVR) and can change at any time. Fixed rates are locked for a term (1–5 years typically), providing repayment certainty. Split loans combine both. Introductory/honeymoon rates offer a discounted variable rate for 1–3 years before reverting to SVR. Interest-only loans require only interest payments for a set period (usually 1–5 years), common for investment properties. Comparison rates (mandated by ASIC) include fees and charges to give a truer cost picture. The RBA cash rate influences all lending rates but banks set their own margins.`,
  `APRA Serviceability Buffer: The Australian Prudential Regulation Authority (APRA) requires banks to assess borrowers' ability to repay at the loan's interest rate plus a buffer of at least 3 percentage points (raised from 2.5% in October 2021). For example, if a loan rate is 6.5%, the bank must verify the borrower can service repayments at 9.5%. This buffer protects against rate rises and reduces maximum borrowing capacity. It applies to all new residential mortgage applications, including refinances, and is a key factor in determining borrowing power. Some lenders apply additional internal buffers beyond the APRA minimum.`,
  `Loan-to-Value Ratio (LVR) and Lenders Mortgage Insurance (LMI): LVR is the loan amount as a percentage of the property value. LVR tiers: ≤60% (lowest risk, best rates), 60–70%, 70–80% (standard), 80–90% (higher rates, LMI usually required), 90–95% (highest rates, LMI mandatory). LMI is a one-off premium paid by the borrower that protects the lender if the borrower defaults. LMI costs range from 1–4% of the loan amount depending on LVR and loan size. First Home Loan Deposit Scheme (FHLDS) allows eligible buyers to purchase with 5% deposit without LMI, government guarantees the remaining 15%.`,
  `ASIC Comparison Rate Rules: Under the National Consumer Credit Protection Act 2009, lenders must display a comparison rate alongside any advertised interest rate. The comparison rate is calculated on a $150,000 loan over 25 years (standardised scenario). It includes the advertised rate plus most ongoing fees and charges (establishment fees, monthly account fees, discharge fees). It excludes: government charges (stamp duty, registration), redraw fees, early repayment fees, and lender's mortgage insurance. Comparison rates help consumers compare the true cost of loans across providers, though they may not perfectly reflect individual circumstances due to the standardised calculation method.`,
  `Offset vs Redraw Accounts: An offset account is a transaction account linked to a home loan where the balance reduces the principal on which interest is calculated. A 100% offset means $50,000 in the offset on a $500,000 loan means interest is charged on $450,000. Redraw allows borrowers to access extra repayments they've made above the minimum. Key differences: Offset funds are instantly accessible with no restrictions; redraw may have minimum amounts or fees. For investment loans, offset is preferred for tax purposes — offset doesn't reduce the loan balance (preserving deductible interest), while redraw technically repays and then re-borrows. Partial offset accounts (e.g., only 40% of balance offsets) exist but are less common.`,
  `Fixed Rate Break Costs in Australia: Breaking a fixed-rate loan early incurs break costs (also called early repayment costs or economic costs). These are calculated based on the difference between the fixed rate and the current wholesale rate for the remaining term. If wholesale rates have dropped since the loan was fixed, break costs can be substantial — potentially tens of thousands of dollars. If rates have risen, break costs may be zero. Formula: Break cost ≈ (Fixed rate – Current wholesale rate) × Remaining term × Loan balance. Most lenders cap extra repayments during a fixed term at $10,000–$25,000 per year without penalty. Borrowers should carefully calculate break costs before refinancing a fixed loan.`,
  `CDR Banking Product Categories: The Consumer Data Right classifies banking products into these categories: RESIDENTIAL_MORTGAGES (home loans for owner-occupier and investment), BUSINESS_LOANS (secured and unsecured business lending), PERSONAL_LOANS (secured and unsecured consumer lending), TRANS_AND_SAVINGS_ACCOUNTS (everyday transaction and savings accounts), TERM_DEPOSITS (fixed-term investments), CRED_AND_CHRG_CARDS (credit cards and charge cards), OVERDRAFTS (overdraft facilities), REGULATED_TRUST_ACCOUNTS (statutory trust accounts), TRADE_FINANCE (import/export financing), TRAVEL_CARDS (multi-currency prepaid cards), MARGIN_LOANS (margin lending for securities). Each category has specific data fields for rates, fees, and features that must be disclosed under CDR.`,
  `RBA Cash Rate and Banking Products: The Reserve Bank of Australia (RBA) sets the cash rate target at monthly meetings (except January). Changes flow through to banking products: Variable home loans typically adjust within 1–2 weeks of a cash rate change. Term deposits adjust based on market expectations of future rates. Credit card rates rarely change with cash rate movements. Savings account rates may be adjusted but with varying lag. Business lending rates follow with some delay. Historically, banks pass on rate increases faster than decreases. Since May 2022, the RBA raised rates rapidly from 0.10% to combat inflation. The cash rate directly affects the bank bill swap rate (BBSW) and the interbank overnight cash rate, which are the underlying benchmarks for variable lending.`,
  `Refinancing Decision Framework: When evaluating whether to refinance a home loan, consider: 1) Rate differential — is the new rate at least 0.25–0.50% lower after comparing true rates (comparison rates)? 2) Break costs — for fixed loans, calculate economic cost vs savings. 3) Switching costs — discharge fee ($150–$350), new application fee, property valuation ($200–$600), legal/settlement fees ($200–$500). 4) Cash-back offers — some lenders offer $2,000–$4,000 but may have higher ongoing rates. 5) Loan features — does the new loan offer offset, redraw, extra repayments, split facility? 6) LVR position — has property value increased enough to reduce LVR tier and eliminate LMI? 7) Clawback clauses — some brokers face commission clawback if the loan is refinanced within 1–2 years. Generally, refinancing is worthwhile if net savings exceed $1,500–$2,000 in the first year.`,
  `Australian Deposit Products and Government Guarantee: The Financial Claims Scheme (FCS) guarantees deposits up to $250,000 per person per ADI (Authorised Deposit-taking Institution). This covers transaction accounts, savings accounts, term deposits, and some other deposit products. Savings account types: Bonus saver (requires monthly deposit and no withdrawals for bonus rate), Goal saver (target balance growth), High-interest online saver (higher rate for online-only), At-call savings (flexible access, lower rate). Term deposit considerations: Early withdrawal penalties apply, interest can be paid monthly, annually, or at maturity. For amounts over $250,000, spreading across multiple ADIs ensures full FCS coverage. The guarantee applies automatically — no need to register.`,
];
