import type { Transaction } from '../../../../api/index.js';

export function generateMockData(): { transactions: Transaction[]; total: number } {
  const mockTx: Transaction[] = [
    {
      id: '1',
      date: '2026-01-15',
      description: 'Client Invoice #1042',
      amount: 4500,
      category: 'Service Revenue',
      gstApplicable: true,
      confidenceScore: 0.95,
    },
    {
      id: '2',
      date: '2026-01-18',
      description: 'Product Sale',
      amount: 2200,
      category: 'Sales Revenue',
      gstApplicable: true,
      confidenceScore: 0.9,
    },
    {
      id: '3',
      date: '2026-01-20',
      description: 'Bank Interest',
      amount: 45,
      category: 'Interest Income',
      gstApplicable: false,
      confidenceScore: 0.99,
    },
    {
      id: '4',
      date: '2026-01-22',
      description: 'Rental Payment Received',
      amount: 1800,
      category: 'Rental Income',
      gstApplicable: true,
      confidenceScore: 0.92,
    },
    {
      id: '5',
      date: '2026-02-01',
      description: 'Freelance Project',
      amount: 3200,
      category: 'Business Income',
      gstApplicable: true,
      confidenceScore: 0.88,
    },
    {
      id: '6',
      date: '2026-02-05',
      description: 'Woolworths',
      amount: -185,
      category: 'Groceries',
      gstApplicable: true,
      confidenceScore: 0.97,
    },
    {
      id: '7',
      date: '2026-02-06',
      description: 'Shell Fuel',
      amount: -95,
      category: 'Fuel',
      gstApplicable: true,
      confidenceScore: 0.95,
    },
    {
      id: '8',
      date: '2026-02-07',
      description: 'Telstra Bill',
      amount: -120,
      category: 'Telephone & Internet',
      gstApplicable: true,
      confidenceScore: 0.96,
    },
    {
      id: '9',
      date: '2026-02-08',
      description: 'Office Rent',
      amount: -2200,
      category: 'Rent',
      gstApplicable: true,
      confidenceScore: 0.98,
    },
    {
      id: '10',
      date: '2026-02-09',
      description: 'AWS Hosting',
      amount: -350,
      category: 'Computer & IT',
      gstApplicable: true,
      confidenceScore: 0.93,
    },
    {
      id: '11',
      date: '2026-02-10',
      description: 'NRMA Insurance',
      amount: -680,
      category: 'Insurance',
      gstApplicable: false,
      confidenceScore: 0.94,
    },
    {
      id: '12',
      date: '2026-02-11',
      description: 'Uber Eats',
      amount: -42,
      category: 'Dining & Takeaway',
      gstApplicable: true,
      confidenceScore: 0.91,
    },
    {
      id: '13',
      date: '2026-02-12',
      description: 'Xero Subscription',
      amount: -65,
      category: 'Software & Subscriptions',
      gstApplicable: true,
      confidenceScore: 0.96,
    },
    {
      id: '14',
      date: '2026-01-25',
      description: 'Client Invoice #1043',
      amount: 6800,
      category: 'Service Revenue',
      gstApplicable: true,
      confidenceScore: 0.94,
    },
    {
      id: '15',
      date: '2026-01-28',
      description: 'Transfer to Savings',
      amount: -2000,
      category: 'Transfer',
      gstApplicable: false,
      confidenceScore: 0.99,
      isTransfer: true,
    },
    {
      id: '16',
      date: '2026-02-03',
      description: 'CPA Accounting Fees',
      amount: -450,
      category: 'Professional Fees',
      gstApplicable: true,
      confidenceScore: 0.92,
    },
    {
      id: '17',
      date: '2026-02-04',
      description: 'Marketing Campaign',
      amount: -320,
      category: 'Advertising & Marketing',
      gstApplicable: true,
      confidenceScore: 0.89,
    },
    {
      id: '18',
      date: '2026-02-06',
      description: 'Bunnings Hardware',
      amount: -175,
      category: 'Home & Garden',
      gstApplicable: true,
      confidenceScore: 0.91,
    },
    {
      id: '19',
      date: '2026-02-07',
      description: 'Staff Wages',
      amount: -3500,
      category: 'Wages & Salaries',
      gstApplicable: false,
      confidenceScore: 0.97,
    },
    {
      id: '20',
      date: '2026-02-10',
      description: 'ATO BAS Payment',
      amount: -1400,
      category: 'Tax Payments',
      gstApplicable: false,
      confidenceScore: 0.98,
    },
    // Older months for sparkline data
    {
      id: '21',
      date: '2025-09-15',
      description: 'Client Work Sep',
      amount: 5200,
      category: 'Service Revenue',
      gstApplicable: true,
      confidenceScore: 0.95,
    },
    {
      id: '22',
      date: '2025-09-20',
      description: 'Rent Sep',
      amount: -2200,
      category: 'Rent',
      gstApplicable: true,
      confidenceScore: 0.98,
    },
    {
      id: '23',
      date: '2025-10-15',
      description: 'Client Work Oct',
      amount: 4800,
      category: 'Service Revenue',
      gstApplicable: true,
      confidenceScore: 0.95,
    },
    {
      id: '24',
      date: '2025-10-22',
      description: 'Rent Oct',
      amount: -2200,
      category: 'Rent',
      gstApplicable: true,
      confidenceScore: 0.98,
    },
    {
      id: '25',
      date: '2025-11-15',
      description: 'Client Work Nov',
      amount: 6100,
      category: 'Service Revenue',
      gstApplicable: true,
      confidenceScore: 0.95,
    },
    {
      id: '26',
      date: '2025-11-20',
      description: 'Rent Nov',
      amount: -2200,
      category: 'Rent',
      gstApplicable: true,
      confidenceScore: 0.98,
    },
    {
      id: '27',
      date: '2025-12-15',
      description: 'Client Work Dec',
      amount: 3900,
      category: 'Service Revenue',
      gstApplicable: true,
      confidenceScore: 0.95,
    },
    {
      id: '28',
      date: '2025-12-22',
      description: 'Rent Dec',
      amount: -2200,
      category: 'Rent',
      gstApplicable: true,
      confidenceScore: 0.98,
    },
  ];
  return { transactions: mockTx, total: mockTx.length };
}
