/**
 * Budget CRUD Operations
 *
 * Create, read, update, delete budgets and budget lines.
 */

import { db, budgets, budgetLines } from '../../schema.js';
import { eq, and, sql } from 'drizzle-orm';
import crypto from 'crypto';
import type { CreateBudgetParams, CreateBudgetLineParams } from './types.js';
import { generateFromHistory } from './budget-generation.js';
import {
  selectOne,
  selectMany,
  update as typedUpdate,
  deleteRows,
} from '../../db/typed-queries.js';

export class BudgetCrud {
  async createBudget(userId: string, params: CreateBudgetParams) {
    const now = new Date().toISOString();
    const budgetId = crypto.randomUUID();

    const newBudget = {
      id: budgetId,
      userId,
      name: params.name,
      budgetType: params.budgetType,
      periodStart: params.periodStart,
      periodEnd: params.periodEnd,
      accountId: params.accountId ?? null,
      totalAmount: 0,
      status: 'draft',
      autoGenerated: params.autoGenerate ?? false,
      sourceMethod: params.autoGenerate ? 'historical_average' : 'manual',
      createdAt: now,
      updatedAt: now,
    };

    await db.insert(budgets).values(newBudget);

    let lines: Awaited<ReturnType<typeof generateFromHistory>> = [];
    if (params.autoGenerate) {
      const lookback = params.lookbackMonths ?? 12;
      lines = await generateFromHistory(
        userId,
        params.periodStart,
        params.periodEnd,
        lookback,
        budgetId,
      );

      // Update total from generated lines
      const total = lines.reduce((sum: number, l: { budgetedAmount: number }) => sum + Math.abs(l.budgetedAmount), 0);
      await db
        .update(budgets)
        .set({ totalAmount: total, updatedAt: new Date().toISOString() })
        .where(eq(budgets.id, budgetId));
    }

    return { ...newBudget, lines };
  }

  async getBudget(budgetId: string): Promise<
    | ({
        id: string;
        lines: Array<typeof budgetLines.$inferSelect>;
        categoryTotals: Record<string, number>;
      } & typeof budgets.$inferSelect)
    | null
  > {
    const budget = await selectOne(db, budgets, eq(budgets.id, budgetId));

    if (!budget) return null;

    const lines = await selectMany(db, budgetLines, eq(budgetLines.budgetId, budgetId));

    // Calculate totals per category
    const categoryTotals = new Map<string, number>();
    for (const line of lines) {
      const current = categoryTotals.get(line.category) ?? 0;
      categoryTotals.set(line.category, current + line.budgetedAmount);
    }

    return {
      ...budget,
      lines,
      categoryTotals: Object.fromEntries(categoryTotals),
    };
  }

  async listBudgets(userId: string, status?: string): Promise<Array<typeof budgets.$inferSelect>> {
    const results: Array<typeof budgets.$inferSelect> = status
      ? await db
          .select()
          .from(budgets)
          .where(and(eq(budgets.userId, userId), eq(budgets.status, status)))
          .orderBy(sql`${budgets.periodStart} DESC`)
          .all()
      : await db
          .select()
          .from(budgets)
          .where(eq(budgets.userId, userId))
          .orderBy(sql`${budgets.periodStart} DESC`)
          .all();

    return results;
  }

  async updateBudget(
    budgetId: string,
    updates: Partial<{ name: string; status: string; periodStart: string; periodEnd: string }>,
  ) {
    const now = new Date().toISOString();

    await db
      .update(budgets)
      .set({ ...updates, updatedAt: now })
      .where(eq(budgets.id, budgetId));

    // Recalculate total from budget lines
    const lines = await db
      .select()
      .from(budgetLines)
      .where(eq(budgetLines.budgetId, budgetId))
      .all();

    const total = lines.reduce(
      (sum: number, l: typeof budgetLines.$inferSelect) => sum + Math.abs(l.budgetedAmount),
      0,
    );
    await db.update(budgets).set({ totalAmount: total }).where(eq(budgets.id, budgetId));

    return this.getBudget(budgetId);
  }

  async deleteBudget(budgetId: string): Promise<void> {
    // CASCADE delete handles budget_lines and budget_vs_actual
    await db.delete(budgets).where(eq(budgets.id, budgetId));
  }

  // --------------------------------------------------------------------------
  // Budget Line Operations
  // --------------------------------------------------------------------------

  async addBudgetLine(budgetId: string, line: CreateBudgetLineParams) {
    const lineId = crypto.randomUUID();
    const now = new Date().toISOString();

    const newLine = {
      id: lineId,
      budgetId,
      category: line.category,
      subcategory: line.subcategory ?? null,
      period: line.period,
      budgetedAmount: line.budgetedAmount,
      notes: line.notes ?? null,
      createdAt: now,
    };

    await db.insert(budgetLines).values(newLine);

    // Recalculate parent budget total
    await this.recalculateBudgetTotal(budgetId);

    return newLine;
  }

  async updateBudgetLine(
    lineId: string,
    updates: Partial<{ budgetedAmount: number; notes: string }>,
  ): Promise<typeof budgetLines.$inferSelect | undefined> {
    await typedUpdate(db, budgetLines, updates, eq(budgetLines.id, lineId));

    // Get line to find parent budget
    const line = await selectOne(db, budgetLines, eq(budgetLines.id, lineId));

    if (line) {
      await this.recalculateBudgetTotal(line.budgetId);
    }

    return selectOne(db, budgetLines, eq(budgetLines.id, lineId));
  }

  async deleteBudgetLine(lineId: string): Promise<void> {
    // Get line to find parent budget before deleting
    const line = await selectOne(db, budgetLines, eq(budgetLines.id, lineId));

    await deleteRows(db, budgetLines, eq(budgetLines.id, lineId));

    if (line) {
      await this.recalculateBudgetTotal(line.budgetId);
    }
  }

  async recalculateBudgetTotal(budgetId: string): Promise<void> {
    const lines = await selectMany(db, budgetLines, eq(budgetLines.budgetId, budgetId));

    const total = lines.reduce(
      (sum: number, l: typeof budgetLines.$inferSelect) => sum + Math.abs(l.budgetedAmount),
      0,
    );

    await typedUpdate(
      db,
      budgets,
      { totalAmount: total, updatedAt: new Date().toISOString() },
      eq(budgets.id, budgetId),
    );
  }
}
