/**
 * Ledger Module — Standard Chart of Accounts (Australian)
 */

export const STANDARD_CHART_OF_ACCOUNTS = [
  // Assets (1-xxxx)
  { code: '1-0000', name: 'Assets', type: 'asset', normalBalance: 'debit' },
  { code: '1-0100', name: 'Cash at Bank', type: 'asset', normalBalance: 'debit' },
  {
    code: '1-0110',
    name: 'Main Transaction Account',
    type: 'asset',
    normalBalance: 'debit',
    parent: '1-0100',
  },
  {
    code: '1-0120',
    name: 'Savings Account',
    type: 'asset',
    normalBalance: 'debit',
    parent: '1-0100',
  },
  { code: '1-0200', name: 'Accounts Receivable', type: 'asset', normalBalance: 'debit' },
  { code: '1-0300', name: 'Prepaid Expenses', type: 'asset', normalBalance: 'debit' },
  { code: '1-0400', name: 'Inventory', type: 'asset', normalBalance: 'debit' },
  { code: '1-0500', name: 'Fixed Assets', type: 'asset', normalBalance: 'debit' },
  {
    code: '1-0510',
    name: 'Office Equipment',
    type: 'asset',
    normalBalance: 'debit',
    parent: '1-0500',
  },
  {
    code: '1-0520',
    name: 'Motor Vehicles',
    type: 'asset',
    normalBalance: 'debit',
    parent: '1-0500',
  },
  {
    code: '1-0530',
    name: 'Computer Equipment',
    type: 'asset',
    normalBalance: 'debit',
    parent: '1-0500',
  },
  { code: '1-0600', name: 'Accumulated Depreciation', type: 'asset', normalBalance: 'credit' },
  // Liabilities (2-xxxx)
  { code: '2-0000', name: 'Liabilities', type: 'liability', normalBalance: 'credit' },
  { code: '2-0100', name: 'Accounts Payable', type: 'liability', normalBalance: 'credit' },
  { code: '2-0200', name: 'Credit Card', type: 'liability', normalBalance: 'credit' },
  {
    code: '2-0300',
    name: 'GST Collected',
    type: 'liability',
    normalBalance: 'credit',
    basLabel: '1A',
  },
  { code: '2-0310', name: 'GST Paid', type: 'liability', normalBalance: 'debit', basLabel: '1B' },
  {
    code: '2-0400',
    name: 'PAYG Withholding',
    type: 'liability',
    normalBalance: 'credit',
    basLabel: 'W2',
  },
  { code: '2-0500', name: 'Superannuation Payable', type: 'liability', normalBalance: 'credit' },
  { code: '2-0600', name: 'Loans Payable', type: 'liability', normalBalance: 'credit' },
  // Equity (3-xxxx)
  { code: '3-0000', name: 'Equity', type: 'equity', normalBalance: 'credit' },
  { code: '3-0100', name: "Owner's Capital", type: 'equity', normalBalance: 'credit' },
  { code: '3-0200', name: "Owner's Drawings", type: 'equity', normalBalance: 'debit' },
  { code: '3-0300', name: 'Retained Earnings', type: 'equity', normalBalance: 'credit' },
  { code: '3-0400', name: 'Current Year Earnings', type: 'equity', normalBalance: 'credit' },
  // Revenue (4-xxxx)
  { code: '4-0000', name: 'Revenue', type: 'revenue', normalBalance: 'credit', basLabel: 'G1' },
  {
    code: '4-0100',
    name: 'Sales Revenue',
    type: 'revenue',
    normalBalance: 'credit',
    taxCode: 'GST',
  },
  {
    code: '4-0200',
    name: 'Service Revenue',
    type: 'revenue',
    normalBalance: 'credit',
    taxCode: 'GST',
  },
  {
    code: '4-0300',
    name: 'Interest Income',
    type: 'revenue',
    normalBalance: 'credit',
    taxCode: 'FRE',
  },
  { code: '4-0400', name: 'Other Income', type: 'revenue', normalBalance: 'credit' },
  {
    code: '4-0500',
    name: 'Export Revenue',
    type: 'revenue',
    normalBalance: 'credit',
    taxCode: 'EXP',
    basLabel: 'G2',
  },
  // Cost of Sales (5-xxxx)
  { code: '5-0000', name: 'Cost of Sales', type: 'cogs', normalBalance: 'debit' },
  {
    code: '5-0100',
    name: 'Cost of Goods Sold',
    type: 'cogs',
    normalBalance: 'debit',
    taxCode: 'GST',
  },
  { code: '5-0200', name: 'Direct Labour', type: 'cogs', normalBalance: 'debit' },
  { code: '5-0300', name: 'Freight Costs', type: 'cogs', normalBalance: 'debit', taxCode: 'GST' },
  // Expenses (6-xxxx)
  { code: '6-0000', name: 'Expenses', type: 'expense', normalBalance: 'debit', basLabel: 'G11' },
  {
    code: '6-0100',
    name: 'Advertising & Marketing',
    type: 'expense',
    normalBalance: 'debit',
    taxCode: 'GST',
  },
  { code: '6-0200', name: 'Bank Fees', type: 'expense', normalBalance: 'debit', taxCode: 'FRE' },
  {
    code: '6-0300',
    name: 'Computer & IT',
    type: 'expense',
    normalBalance: 'debit',
    taxCode: 'GST',
  },
  { code: '6-0400', name: 'Depreciation', type: 'expense', normalBalance: 'debit', taxCode: 'N-T' },
  {
    code: '6-0500',
    name: 'Entertainment',
    type: 'expense',
    normalBalance: 'debit',
    taxCode: 'GST',
  },
  { code: '6-0600', name: 'Insurance', type: 'expense', normalBalance: 'debit', taxCode: 'FRE' },
  {
    code: '6-0700',
    name: 'Interest Expense',
    type: 'expense',
    normalBalance: 'debit',
    taxCode: 'FRE',
  },
  {
    code: '6-0800',
    name: 'Motor Vehicle Expenses',
    type: 'expense',
    normalBalance: 'debit',
    taxCode: 'GST',
  },
  {
    code: '6-0900',
    name: 'Office Supplies',
    type: 'expense',
    normalBalance: 'debit',
    taxCode: 'GST',
  },
  {
    code: '6-1000',
    name: 'Professional Fees',
    type: 'expense',
    normalBalance: 'debit',
    taxCode: 'GST',
  },
  { code: '6-1100', name: 'Rent', type: 'expense', normalBalance: 'debit', taxCode: 'GST' },
  {
    code: '6-1200',
    name: 'Repairs & Maintenance',
    type: 'expense',
    normalBalance: 'debit',
    taxCode: 'GST',
  },
  {
    code: '6-1300',
    name: 'Subscriptions',
    type: 'expense',
    normalBalance: 'debit',
    taxCode: 'GST',
  },
  {
    code: '6-1400',
    name: 'Telephone & Internet',
    type: 'expense',
    normalBalance: 'debit',
    taxCode: 'GST',
  },
  { code: '6-1500', name: 'Travel', type: 'expense', normalBalance: 'debit', taxCode: 'GST' },
  { code: '6-1600', name: 'Utilities', type: 'expense', normalBalance: 'debit', taxCode: 'GST' },
  {
    code: '6-1700',
    name: 'Wages & Salaries',
    type: 'expense',
    normalBalance: 'debit',
    taxCode: 'N-T',
    basLabel: 'W1',
  },
  {
    code: '6-1800',
    name: 'Superannuation',
    type: 'expense',
    normalBalance: 'debit',
    taxCode: 'N-T',
  },
  {
    code: '6-1900',
    name: 'Work from Home Expenses',
    type: 'expense',
    normalBalance: 'debit',
    taxCode: 'N-T',
  },
  { code: '6-2000', name: 'Miscellaneous', type: 'expense', normalBalance: 'debit' },
];
