-- =============================================================================
-- PostgreSQL Migration Schema for AI Accountant
-- =============================================================================
-- This migration creates the PostgreSQL schema for the AI Accountant fintech
-- application, previously running on SQLite.
--
-- Key Design Decisions:
-- - UUIDs stored as TEXT (application generates them, not database)
-- - Currency amounts stored as INTEGER (cents) to avoid floating-point errors
-- - All timestamps use TIMESTAMPTZ for timezone awareness
-- - Appropriate indexes for common query patterns
-- - Foreign key constraints with appropriate ON DELETE behavior
--
-- Run with: psql -d ai_accountant -f 0006_postgres_migration.sql
-- =============================================================================

-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pg_trgm"; -- For fuzzy text search on merchant names

-- =============================================================================
-- DROP EXISTING TABLES (for clean migration)
-- =============================================================================
-- Uncomment if you want to drop existing tables first
-- WARNING: This will delete all existing data!

-- DROP TABLE IF EXISTS debt_payoff_scenarios CASCADE;
-- DROP TABLE IF EXISTS account_balance_history CASCADE;
-- DROP TABLE IF EXISTS reconciliation_alerts CASCADE;
-- DROP TABLE IF EXISTS pending_categorization CASCADE;
-- DROP TABLE IF EXISTS merchant_memory CASCADE;
-- DROP TABLE IF EXISTS user_categories CASCADE;
-- DROP TABLE IF EXISTS transfer_links CASCADE;
-- DROP TABLE IF EXISTS transaction_history CASCADE;
-- DROP TABLE IF EXISTS transactions CASCADE;
-- DROP TABLE IF EXISTS statement_accounts CASCADE;
-- DROP TABLE IF EXISTS statements CASCADE;
-- DROP TABLE IF EXISTS accounts CASCADE;
-- DROP TABLE IF EXISTS user_settings CASCADE;
-- DROP TABLE IF EXISTS users CASCADE;

-- =============================================================================
-- USERS & AUTHENTICATION
-- =============================================================================

CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY,
    username TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT users_username_unique UNIQUE (username)
);

COMMENT ON TABLE users IS 'User accounts for the AI Accountant application';
COMMENT ON COLUMN users.id IS 'UUID generated by the application';
COMMENT ON COLUMN users.password_hash IS 'bcrypt hashed password';

CREATE TABLE IF NOT EXISTS user_settings (
    user_id TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    model_parsing_text TEXT NOT NULL DEFAULT 'google/gemini-3-flash-preview',
    model_parsing_vision TEXT NOT NULL DEFAULT 'google/gemini-3-flash-preview',
    model_categorization TEXT NOT NULL DEFAULT 'google/gemini-3-flash-preview',
    model_chat TEXT NOT NULL DEFAULT 'google/gemini-3-flash-preview',
    model_embedding TEXT NOT NULL DEFAULT 'openai/text-embedding-3-large'
);

COMMENT ON TABLE user_settings IS 'AI model preferences per user';
COMMENT ON COLUMN user_settings.model_parsing_text IS 'Model used for text-based statement parsing';
COMMENT ON COLUMN user_settings.model_parsing_vision IS 'Model used for vision-based PDF parsing';

-- =============================================================================
-- ACCOUNTS
-- =============================================================================

CREATE TABLE IF NOT EXISTS accounts (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    account_number TEXT NOT NULL,
    account_number_hash TEXT NOT NULL,
    account_name TEXT NOT NULL,
    account_type TEXT NOT NULL, -- 'checking', 'savings', 'credit_card', 'loan'
    bank_name TEXT,
    current_balance INTEGER DEFAULT 0, -- Stored in cents (AUD)
    last_statement_date TEXT,
    interest_rate REAL, -- Decimal (e.g., 0.0525 for 5.25%)
    credit_limit INTEGER, -- Stored in cents (AUD)
    minimum_payment INTEGER, -- Stored in cents (AUD)
    payment_due_day INTEGER,
    linked_payment_account_id TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE accounts IS 'Bank accounts linked by users';
COMMENT ON COLUMN accounts.current_balance IS 'Balance in cents (Australian dollars). Positive = credit, negative = debit';
COMMENT ON COLUMN accounts.account_number_hash IS 'SHA-256 hash for duplicate detection without storing full number';
COMMENT ON COLUMN accounts.interest_rate IS 'Annual interest rate as decimal (0.0525 = 5.25%)';

CREATE INDEX IF NOT EXISTS accounts_user_id_idx ON accounts(user_id);
CREATE INDEX IF NOT EXISTS accounts_hash_idx ON accounts(account_number_hash);

CREATE TABLE IF NOT EXISTS account_balance_history (
    id TEXT PRIMARY KEY,
    account_id TEXT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    balance INTEGER NOT NULL, -- Stored in cents (AUD)
    balance_date TEXT NOT NULL, -- ISO date YYYY-MM-DD
    source TEXT NOT NULL, -- 'statement', 'manual', 'calculated'
    statement_id TEXT,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE account_balance_history IS 'Historical balance snapshots for reconciliation';
COMMENT ON COLUMN account_balance_history.balance IS 'Balance in cents at the specified date';

CREATE INDEX IF NOT EXISTS balance_history_account_date_idx ON account_balance_history(account_id, balance_date);

-- =============================================================================
-- STATEMENTS
-- =============================================================================

CREATE TABLE IF NOT EXISTS statements (
    id TEXT PRIMARY KEY,
    filename TEXT NOT NULL,
    hash TEXT NOT NULL,
    upload_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    parsing_status TEXT NOT NULL DEFAULT 'PENDING', -- 'PENDING', 'PROCESSING', 'COMPLETED', 'FAILED'
    ai_model_used TEXT,
    error_message TEXT,
    error_type TEXT,
    error_details TEXT, -- JSON for structured error info
    user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
    period_start_date TEXT, -- ISO date YYYY-MM-DD
    period_end_date TEXT,   -- ISO date YYYY-MM-DD
    opening_balance INTEGER, -- Stored in cents (AUD)
    closing_balance INTEGER, -- Stored in cents (AUD)
    transaction_count INTEGER DEFAULT 0,
    is_complete BOOLEAN DEFAULT TRUE,
    validation_errors TEXT, -- JSON array of validation errors

    CONSTRAINT statements_hash_unique UNIQUE (hash)
);

COMMENT ON TABLE statements IS 'Uploaded bank statements (PDF, CSV, OFX, QIF)';
COMMENT ON COLUMN statements.hash IS 'SHA-256 hash for duplicate detection';
COMMENT ON COLUMN statements.opening_balance IS 'Opening balance from statement in cents';
COMMENT ON COLUMN statements.closing_balance IS 'Closing balance from statement in cents';

CREATE INDEX IF NOT EXISTS statements_user_id_idx ON statements(user_id);
CREATE INDEX IF NOT EXISTS statements_upload_date_idx ON statements(upload_date);
CREATE INDEX IF NOT EXISTS statements_user_date_idx ON statements(user_id, upload_date);
CREATE INDEX IF NOT EXISTS statements_period_idx ON statements(period_start_date, period_end_date);

-- Junction table for statements that contain multiple accounts
CREATE TABLE IF NOT EXISTS statement_accounts (
    statement_id TEXT PRIMARY KEY REFERENCES statements(id) ON DELETE CASCADE,
    account_id TEXT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE
);

COMMENT ON TABLE statement_accounts IS 'Links statements to accounts (for multi-account statements)';

-- Add foreign key for account_balance_history -> statements
ALTER TABLE account_balance_history
    ADD CONSTRAINT account_balance_history_statement_id_fk
    FOREIGN KEY (statement_id) REFERENCES statements(id) ON DELETE SET NULL;

-- =============================================================================
-- TRANSACTIONS
-- =============================================================================

CREATE TABLE IF NOT EXISTS transactions (
    id TEXT PRIMARY KEY,
    date TEXT NOT NULL, -- ISO date YYYY-MM-DD
    description TEXT NOT NULL,
    amount INTEGER NOT NULL, -- Stored in cents. Positive = credit, negative = debit
    balance INTEGER, -- Running balance in cents
    category TEXT,
    gst_applicable BOOLEAN DEFAULT FALSE,
    ai_reasoning_notes TEXT,
    confidence_score REAL DEFAULT 1.0, -- 0.0 to 1.0
    is_edited BOOLEAN DEFAULT FALSE,
    is_transfer BOOLEAN DEFAULT FALSE,
    transfer_link_id TEXT,
    merchant_normalized TEXT,
    parent_transaction_id TEXT,
    statement_id TEXT REFERENCES statements(id) ON DELETE SET NULL,
    account_id TEXT REFERENCES accounts(id) ON DELETE SET NULL,
    user_id TEXT REFERENCES users(id) ON DELETE SET NULL
);

COMMENT ON TABLE transactions IS 'Individual financial transactions parsed from statements';
COMMENT ON COLUMN transactions.amount IS 'Amount in cents. Positive = credit/income, negative = debit/expense';
COMMENT ON COLUMN transactions.balance IS 'Running balance after this transaction, in cents';
COMMENT ON COLUMN transactions.gst_applicable IS 'Whether GST (10% Australian goods and services tax) applies';
COMMENT ON COLUMN transactions.confidence_score IS 'AI categorization confidence (1.0 = certain, 0.0 = guess)';
COMMENT ON COLUMN transactions.merchant_normalized IS 'Cleaned merchant name for grouping';

CREATE INDEX IF NOT EXISTS transactions_date_idx ON transactions(date);
CREATE INDEX IF NOT EXISTS transactions_user_id_idx ON transactions(user_id);
CREATE INDEX IF NOT EXISTS transactions_statement_id_idx ON transactions(statement_id);
CREATE INDEX IF NOT EXISTS transactions_category_idx ON transactions(category);
CREATE INDEX IF NOT EXISTS transactions_user_date_idx ON transactions(user_id, date);
CREATE INDEX IF NOT EXISTS transactions_account_id_idx ON transactions(account_id);
CREATE INDEX IF NOT EXISTS transactions_transfer_idx ON transactions(is_transfer, transfer_link_id);

-- Trigram index for fuzzy merchant search
CREATE INDEX IF NOT EXISTS transactions_merchant_trgm_idx ON transactions
    USING gin (merchant_normalized gin_trgm_ops);

CREATE TABLE IF NOT EXISTS transaction_history (
    id TEXT PRIMARY KEY,
    transaction_id TEXT REFERENCES transactions(id) ON DELETE SET NULL,
    change_type TEXT NOT NULL, -- 'create', 'update', 'delete', 'split', 'merge'
    old_data TEXT, -- JSON
    new_data TEXT, -- JSON
    timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE transaction_history IS 'Audit trail for transaction changes';

CREATE INDEX IF NOT EXISTS transaction_history_transaction_idx ON transaction_history(transaction_id);
CREATE INDEX IF NOT EXISTS transaction_history_timestamp_idx ON transaction_history(timestamp);

-- =============================================================================
-- TRANSFERS
-- =============================================================================

CREATE TABLE IF NOT EXISTS transfer_links (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    source_transaction_id TEXT NOT NULL REFERENCES transactions(id) ON DELETE CASCADE,
    destination_transaction_id TEXT NOT NULL REFERENCES transactions(id) ON DELETE CASCADE,
    source_account_id TEXT REFERENCES accounts(id) ON DELETE SET NULL,
    destination_account_id TEXT REFERENCES accounts(id) ON DELETE SET NULL,
    amount INTEGER NOT NULL, -- Stored in cents (AUD)
    transfer_date TEXT NOT NULL, -- ISO date YYYY-MM-DD
    confidence REAL DEFAULT 1.0,
    is_user_confirmed BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE transfer_links IS 'Links matching debit/credit transactions as internal transfers';
COMMENT ON COLUMN transfer_links.amount IS 'Transfer amount in cents (absolute value)';
COMMENT ON COLUMN transfer_links.confidence IS 'AI confidence in transfer detection (1.0 = certain)';

CREATE INDEX IF NOT EXISTS transfer_links_user_idx ON transfer_links(user_id);
CREATE INDEX IF NOT EXISTS transfer_links_source_idx ON transfer_links(source_transaction_id);
CREATE INDEX IF NOT EXISTS transfer_links_dest_idx ON transfer_links(destination_transaction_id);

-- =============================================================================
-- CATEGORIZATION
-- =============================================================================

CREATE TABLE IF NOT EXISTS user_categories (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    category_name TEXT NOT NULL,
    parent_category TEXT,
    icon TEXT,
    color TEXT,
    is_income BOOLEAN DEFAULT FALSE,
    is_transfer BOOLEAN DEFAULT FALSE,
    is_hidden BOOLEAN DEFAULT FALSE,
    sort_order INTEGER DEFAULT 0
);

COMMENT ON TABLE user_categories IS 'Custom user-defined transaction categories';

CREATE INDEX IF NOT EXISTS user_categories_idx ON user_categories(user_id, category_name);

CREATE TABLE IF NOT EXISTS merchant_memory (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    merchant_pattern TEXT NOT NULL,
    merchant_display_name TEXT,
    category TEXT NOT NULL,
    gst_applicable BOOLEAN DEFAULT FALSE,
    times_used INTEGER DEFAULT 1,
    last_used TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    is_user_confirmed BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE merchant_memory IS 'Learned merchant to category mappings per user';
COMMENT ON COLUMN merchant_memory.merchant_pattern IS 'Pattern or normalized merchant name to match';
COMMENT ON COLUMN merchant_memory.times_used IS 'Number of times this mapping was applied';

CREATE INDEX IF NOT EXISTS merchant_user_pattern_idx ON merchant_memory(user_id, merchant_pattern);
CREATE INDEX IF NOT EXISTS merchant_category_idx ON merchant_memory(category);

-- Trigram index for fuzzy merchant pattern matching
CREATE INDEX IF NOT EXISTS merchant_pattern_trgm_idx ON merchant_memory
    USING gin (merchant_pattern gin_trgm_ops);

CREATE TABLE IF NOT EXISTS pending_categorization (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    transaction_id TEXT NOT NULL REFERENCES transactions(id) ON DELETE CASCADE,
    suggested_category TEXT,
    suggested_confidence REAL,
    ai_reasoning TEXT,
    alternative_categories TEXT, -- JSON array
    status TEXT NOT NULL DEFAULT 'pending', -- 'pending', 'approved', 'rejected', 'skipped'
    user_selected_category TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    resolved_at TIMESTAMPTZ
);

COMMENT ON TABLE pending_categorization IS 'Queue of transactions awaiting user categorization review';

CREATE INDEX IF NOT EXISTS pending_cat_user_status_idx ON pending_categorization(user_id, status);
CREATE INDEX IF NOT EXISTS pending_cat_transaction_idx ON pending_categorization(transaction_id);

-- =============================================================================
-- RECONCILIATION
-- =============================================================================

CREATE TABLE IF NOT EXISTS reconciliation_alerts (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    account_id TEXT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    alert_type TEXT NOT NULL, -- 'balance_mismatch', 'duplicate_transaction', 'missing_transaction', 'gap_detected'
    expected_value INTEGER, -- Stored in cents (AUD)
    actual_value INTEGER,   -- Stored in cents (AUD)
    difference INTEGER,     -- Stored in cents (AUD)
    description TEXT NOT NULL,
    statement_id TEXT REFERENCES statements(id) ON DELETE SET NULL,
    is_resolved BOOLEAN DEFAULT FALSE,
    resolved_at TIMESTAMPTZ,
    resolution_notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE reconciliation_alerts IS 'Discrepancies and anomalies detected during statement processing';
COMMENT ON COLUMN reconciliation_alerts.expected_value IS 'Expected value in cents';
COMMENT ON COLUMN reconciliation_alerts.actual_value IS 'Actual value found in cents';
COMMENT ON COLUMN reconciliation_alerts.difference IS 'Difference in cents (can be negative)';

CREATE INDEX IF NOT EXISTS reconciliation_user_idx ON reconciliation_alerts(user_id, is_resolved);
CREATE INDEX IF NOT EXISTS reconciliation_account_idx ON reconciliation_alerts(account_id);

-- =============================================================================
-- DEBT MANAGEMENT
-- =============================================================================

CREATE TABLE IF NOT EXISTS debt_payoff_scenarios (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    strategy TEXT NOT NULL, -- 'avalanche', 'snowball', 'custom'
    accounts_included TEXT NOT NULL, -- JSON array of account IDs
    monthly_budget INTEGER, -- Stored in cents (AUD)
    projected_payoff_date TEXT, -- ISO date YYYY-MM-DD
    total_interest_cost INTEGER, -- Stored in cents (AUD)
    total_payments INTEGER,      -- Stored in cents (AUD)
    monthly_breakdown TEXT, -- JSON with payment schedule
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE debt_payoff_scenarios IS 'Debt payoff strategy scenarios for financial planning';
COMMENT ON COLUMN debt_payoff_scenarios.strategy IS 'avalanche=highest interest first, snowball=smallest balance first';
COMMENT ON COLUMN debt_payoff_scenarios.monthly_budget IS 'Total monthly debt payment budget in cents';

CREATE INDEX IF NOT EXISTS debt_scenario_user_idx ON debt_payoff_scenarios(user_id);

-- =============================================================================
-- HELPER FUNCTIONS
-- =============================================================================

-- Function to convert cents to dollars for display
CREATE OR REPLACE FUNCTION cents_to_dollars(cents INTEGER)
RETURNS NUMERIC(12,2) AS $$
BEGIN
    IF cents IS NULL THEN
        RETURN NULL;
    END IF;
    RETURN cents / 100.0;
END;
$$ LANGUAGE plpgsql IMMUTABLE;

COMMENT ON FUNCTION cents_to_dollars IS 'Convert cents (INTEGER) to dollars (NUMERIC) for display';

-- Function to convert dollars to cents for storage
CREATE OR REPLACE FUNCTION dollars_to_cents(dollars NUMERIC)
RETURNS INTEGER AS $$
BEGIN
    IF dollars IS NULL THEN
        RETURN NULL;
    END IF;
    RETURN ROUND(dollars * 100)::INTEGER;
END;
$$ LANGUAGE plpgsql IMMUTABLE;

COMMENT ON FUNCTION dollars_to_cents IS 'Convert dollars (NUMERIC) to cents (INTEGER) for storage';

-- Function to calculate GST amount (Australian 10%)
CREATE OR REPLACE FUNCTION calculate_gst(amount_cents INTEGER)
RETURNS INTEGER AS $$
BEGIN
    IF amount_cents IS NULL THEN
        RETURN NULL;
    END IF;
    -- GST = Amount / 11 (since GST-inclusive amount = base + 10% = base * 1.1)
    RETURN ROUND(amount_cents / 11.0)::INTEGER;
END;
$$ LANGUAGE plpgsql IMMUTABLE;

COMMENT ON FUNCTION calculate_gst IS 'Calculate GST component from a GST-inclusive amount in cents (Australian 10% GST)';

-- =============================================================================
-- UPDATED_AT TRIGGER
-- =============================================================================

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Apply trigger to tables with updated_at column
DROP TRIGGER IF EXISTS update_users_updated_at ON users;
CREATE TRIGGER update_users_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_accounts_updated_at ON accounts;
CREATE TRIGGER update_accounts_updated_at
    BEFORE UPDATE ON accounts
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_debt_payoff_scenarios_updated_at ON debt_payoff_scenarios;
CREATE TRIGGER update_debt_payoff_scenarios_updated_at
    BEFORE UPDATE ON debt_payoff_scenarios
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- =============================================================================
-- GRANTS (adjust as needed for your user/roles)
-- =============================================================================

-- Example: Grant all privileges to application user
-- GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ai_accountant_app;
-- GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO ai_accountant_app;
-- GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO ai_accountant_app;

-- =============================================================================
-- VERIFICATION QUERIES
-- =============================================================================

-- Run these after migration to verify schema was created correctly:
-- SELECT table_name FROM information_schema.tables WHERE table_schema = 'public';
-- SELECT column_name, data_type, is_nullable FROM information_schema.columns WHERE table_name = 'transactions';
