#!/usr/bin/env python3
"""Fetch remaining skills not yet downloaded"""
import os
import sys
from pathlib import Path
import urllib.request
import urllib.error

SKILLS_DIR = Path(__file__).parent
OK = 0
FAIL = 0

def get_skill(name, repo, path, branch="main"):
    global OK, FAIL
    out = SKILLS_DIR / f"{name}.md"
    
    if out.exists():
        print(f"  ✓ (exists) {name}")
        OK += 1
        return
    
    url = f"https://raw.githubusercontent.com/{repo}/{branch}/{path}"
    
    try:
        with urllib.request.urlopen(url, timeout=10) as response:
            content = response.read().decode('utf-8')
            out.write_text(content, encoding='utf-8')
            print(f"  ✓ {name}")
            OK += 1
            return
    except (urllib.error.URLError, urllib.error.HTTPError):
        pass
    
    # Try master branch
    url = f"https://raw.githubusercontent.com/{repo}/master/{path}"
    try:
        with urllib.request.urlopen(url, timeout=10) as response:
            content = response.read().decode('utf-8')
            out.write_text(content, encoding='utf-8')
            print(f"  ✓ {name}")
            OK += 1
    except (urllib.error.URLError, urllib.error.HTTPError):
        print(f"  ✗ {name} (failed to fetch)")
        FAIL += 1

print()
print("=== Fetching Remaining Skills ===")
print()

print("[ Trail of Bits - Security ]")
get_skill("tob-ask-questions", "trailofbits/skills", "plugins/ask-questions-if-underspecified/SKILL.md")
get_skill("tob-audit-context", "trailofbits/skills", "plugins/audit-context-building/SKILL.md")
get_skill("tob-secure-contracts", "trailofbits/skills", "plugins/building-secure-contracts/SKILL.md")
get_skill("tob-constant-time", "trailofbits/skills", "plugins/constant-time-analysis/SKILL.md")
get_skill("tob-differential-review", "trailofbits/skills", "plugins/differential-review/SKILL.md")
get_skill("tob-fix-review", "trailofbits/skills", "plugins/fix-review/SKILL.md")
get_skill("tob-insecure-defaults", "trailofbits/skills", "plugins/insecure-defaults/SKILL.md")
get_skill("tob-modern-python", "trailofbits/skills", "plugins/modern-python/SKILL.md")
get_skill("tob-property-testing", "trailofbits/skills", "plugins/property-based-testing/SKILL.md")
get_skill("tob-semgrep-creator", "trailofbits/skills", "plugins/semgrep-rule-creator/SKILL.md")
get_skill("tob-sharp-edges", "trailofbits/skills", "plugins/sharp-edges/SKILL.md")
get_skill("tob-static-analysis", "trailofbits/skills", "plugins/static-analysis/SKILL.md")
get_skill("tob-testing-handbook", "trailofbits/skills", "plugins/testing-handbook-skills/SKILL.md")
get_skill("tob-variant-analysis", "trailofbits/skills", "plugins/variant-analysis/SKILL.md")
get_skill("tob-entry-point", "trailofbits/skills", "plugins/entry-point-analyzer/SKILL.md")
get_skill("tob-burpsuite", "trailofbits/skills", "plugins/burpsuite-project-parser/SKILL.md")
get_skill("tob-firebase-scanner", "trailofbits/skills", "plugins/firebase-apk-scanner/SKILL.md")
get_skill("tob-spec-compliance", "trailofbits/skills", "plugins/spec-to-code-compliance/SKILL.md")

print()
print("[ Expo ]")
get_skill("expo-app-design", "expo/skills", "plugins/expo-app-design/SKILL.md")
get_skill("expo-deployment", "expo/skills", "plugins/expo-deployment/SKILL.md")
get_skill("expo-upgrade", "expo/skills", "plugins/upgrading-expo/SKILL.md")

print()
print("[ Sentry ]")
get_skill("sentry-agents-md", "getsentry/skills", "plugins/sentry-skills/skills/agents-md/SKILL.md")
get_skill("sentry-code-review", "getsentry/skills", "plugins/sentry-skills/skills/code-review/SKILL.md")
get_skill("sentry-commit", "getsentry/skills", "plugins/sentry-skills/skills/commit/SKILL.md")
get_skill("sentry-create-pr", "getsentry/skills", "plugins/sentry-skills/skills/create-pr/SKILL.md")
get_skill("sentry-find-bugs", "getsentry/skills", "plugins/sentry-skills/skills/find-bugs/SKILL.md")
get_skill("sentry-iterate-pr", "getsentry/skills", "plugins/sentry-skills/skills/iterate-pr/SKILL.md")

print()
print("[ Better Auth ]")
get_skill("better-auth-best-practices", "better-auth/skills", "better-auth/best-practices/SKILL.md")
get_skill("better-auth-commands", "better-auth/skills", "better-auth/commands/SKILL.md")
get_skill("better-auth-create-auth", "better-auth/skills", "better-auth/create-auth/SKILL.md")

print()
print("[ Tinybird ]")
get_skill("tinybird-best-practices", "tinybirdco/tinybird-agent-skills", "skills/tinybird-best-practices/SKILL.md")

print()
print("[ Neon ]")
get_skill("neon-postgres", "neondatabase/agent-skills", "skills/neon-postgres/SKILL.md")

print()
print("[ HashiCorp / Terraform ]")
get_skill("terraform-code-gen", "hashicorp/agent-skills", "terraform/code-generation/SKILL.md")
get_skill("terraform-module-gen", "hashicorp/agent-skills", "terraform/module-generation/SKILL.md")
get_skill("terraform-provider", "hashicorp/agent-skills", "terraform/provider-development/SKILL.md")

print()
print("[ Sanity ]")
get_skill("sanity-best-practices", "sanity-io/agent-toolkit", "skills/sanity-best-practices/SKILL.md")
get_skill("sanity-content-modeling", "sanity-io/agent-toolkit", "skills/content-modeling-best-practices/SKILL.md")
get_skill("sanity-seo", "sanity-io/agent-toolkit", "skills/seo-aeo-best-practices/SKILL.md")
get_skill("sanity-experimentation", "sanity-io/agent-toolkit", "skills/content-experimentation-best-practices/SKILL.md")

print()
print("[ Remotion ]")
get_skill("remotion-video", "remotion-dev/skills", "skills/remotion/SKILL.md")

print()
print("[ WordPress ]")
get_skill("wp-router", "WordPress/agent-skills", "skills/wordpress-router/SKILL.md", "trunk")
get_skill("wp-triage", "WordPress/agent-skills", "skills/wp-project-triage/SKILL.md", "trunk")
get_skill("wp-block-dev", "WordPress/agent-skills", "skills/wp-block-development/SKILL.md", "trunk")
get_skill("wp-block-themes", "WordPress/agent-skills", "skills/wp-block-themes/SKILL.md", "trunk")
get_skill("wp-plugin-dev", "WordPress/agent-skills", "skills/wp-plugin-development/SKILL.md", "trunk")
get_skill("wp-rest-api", "WordPress/agent-skills", "skills/wp-rest-api/SKILL.md", "trunk")
get_skill("wp-interactivity", "WordPress/agent-skills", "skills/wp-interactivity-api/SKILL.md", "trunk")
get_skill("wp-abilities", "WordPress/agent-skills", "skills/wp-abilities-api/SKILL.md", "trunk")
get_skill("wp-cli", "WordPress/agent-skills", "skills/wp-wpcli-and-ops/SKILL.md", "trunk")
get_skill("wp-performance", "WordPress/agent-skills", "skills/wp-performance/SKILL.md", "trunk")
get_skill("wp-phpstan", "WordPress/agent-skills", "skills/wp-phpstan/SKILL.md", "trunk")
get_skill("wp-playground", "WordPress/agent-skills", "skills/wp-playground/SKILL.md", "trunk")
get_skill("wp-design-system", "WordPress/agent-skills", "skills/wpds/SKILL.md", "trunk")

print()
print("[ Transloadit ]")
get_skill("transloadit-main", "transloadit/skills", "skills/transloadit/SKILL.md")
get_skill("transloadit-robots", "transloadit/skills", "skills/docs-transloadit-robots/SKILL.md")
get_skill("transloadit-image-gen", "transloadit/skills", "skills/transform-generate-image-with-transloadit/SKILL.md")
get_skill("transloadit-hls", "transloadit/skills", "skills/transform-encode-hls-video-with-transloadit/SKILL.md")
get_skill("transloadit-uppy", "transloadit/skills", "skills/integrate-uppy-transloadit-s3-uploading-to-nextjs/SKILL.md")
get_skill("transloadit-smartcdn", "transloadit/skills", "skills/integrate-asset-delivery-with-transloadit-smartcdn-in-nextjs/SKILL.md")

print()
print("[ Firecrawl ]")
get_skill("firecrawl-cli", "firecrawl/cli", "skills/firecrawl-cli/SKILL.md")

print()
print("[ OpenAI Curated ]")
get_skill("openai-cloudflare-deploy", "openai/skills", "skills/.curated/cloudflare-deploy/SKILL.md")
get_skill("openai-develop-web-game", "openai/skills", "skills/.curated/develop-web-game/SKILL.md")
get_skill("openai-doc", "openai/skills", "skills/.curated/doc/SKILL.md")
get_skill("openai-figma-implement", "openai/skills", "skills/.curated/figma-implement-design/SKILL.md")
get_skill("openai-figma", "openai/skills", "skills/.curated/figma/SKILL.md")
get_skill("openai-gh-address-comments", "openai/skills", "skills/.curated/gh-address-comments/SKILL.md")
get_skill("openai-gh-fix-ci", "openai/skills", "skills/.curated/gh-fix-ci/SKILL.md")
get_skill("openai-imagegen", "openai/skills", "skills/.curated/imagegen/SKILL.md")
get_skill("openai-jupyter", "openai/skills", "skills/.curated/jupyter-notebook/SKILL.md")
get_skill("openai-linear", "openai/skills", "skills/.curated/linear/SKILL.md")
get_skill("openai-netlify-deploy", "openai/skills", "skills/.curated/netlify-deploy/SKILL.md")
get_skill("openai-notion-capture", "openai/skills", "skills/.curated/notion-knowledge-capture/SKILL.md")
get_skill("openai-notion-meeting", "openai/skills", "skills/.curated/notion-meeting-intelligence/SKILL.md")
get_skill("openai-notion-research", "openai/skills", "skills/.curated/notion-research-documentation/SKILL.md")
get_skill("openai-notion-spec", "openai/skills", "skills/.curated/notion-spec-to-implementation/SKILL.md")
get_skill("openai-docs", "openai/skills", "skills/.curated/openai-docs/SKILL.md")
get_skill("openai-pdf", "openai/skills", "skills/.curated/pdf/SKILL.md")
get_skill("openai-playwright", "openai/skills", "skills/.curated/playwright/SKILL.md")
get_skill("openai-render-deploy", "openai/skills", "skills/.curated/render-deploy/SKILL.md")
get_skill("openai-screenshot", "openai/skills", "skills/.curated/screenshot/SKILL.md")
get_skill("openai-security-best", "openai/skills", "skills/.curated/security-best-practices/SKILL.md")
get_skill("openai-security-threat", "openai/skills", "skills/.curated/security-threat-model/SKILL.md")
get_skill("openai-sentry", "openai/skills", "skills/.curated/sentry/SKILL.md")
get_skill("openai-sora", "openai/skills", "skills/.curated/sora/SKILL.md")
get_skill("openai-speech", "openai/skills", "skills/.curated/speech/SKILL.md")
get_skill("openai-spreadsheet", "openai/skills", "skills/.curated/spreadsheet/SKILL.md")
get_skill("openai-transcribe", "openai/skills", "skills/.curated/transcribe/SKILL.md")
get_skill("openai-vercel-deploy", "openai/skills", "skills/.curated/vercel-deploy/SKILL.md")
get_skill("openai-yeet", "openai/skills", "skills/.curated/yeet/SKILL.md")

print()
print("[ fal.ai ]")
get_skill("fal-audio", "fal-ai-community/skills", "skills/claude.ai/fal-audio/SKILL.md")
get_skill("fal-generate", "fal-ai-community/skills", "skills/claude.ai/fal-generate/SKILL.md")
get_skill("fal-image-edit", "fal-ai-community/skills", "skills/claude.ai/fal-image-edit/SKILL.md")
get_skill("fal-platform", "fal-ai-community/skills", "skills/claude.ai/fal-platform/SKILL.md")
get_skill("fal-upscale", "fal-ai-community/skills", "skills/claude.ai/fal-upscale/SKILL.md")
get_skill("fal-workflow", "fal-ai-community/skills", "skills/claude.ai/fal-workflow/SKILL.md")

print()
print("[ obra/superpowers ]")
get_skill("obra-brainstorming", "obra/superpowers", "skills/brainstorming/SKILL.md")
get_skill("obra-writing-plans", "obra/superpowers", "skills/writing-plans/SKILL.md")
get_skill("obra-executing-plans", "obra/superpowers", "skills/executing-plans/SKILL.md")
get_skill("obra-parallel-agents", "obra/superpowers", "skills/dispatching-parallel-agents/SKILL.md")
get_skill("obra-sharing-skills", "obra/superpowers", "skills/sharing-skills/SKILL.md")
get_skill("obra-using-superpowers", "obra/superpowers", "skills/using-superpowers/SKILL.md")
get_skill("obra-tdd", "obra/superpowers", "skills/test-driven-development/SKILL.md")
get_skill("obra-subagent-dev", "obra/superpowers", "skills/subagent-driven-development/SKILL.md")
get_skill("obra-systematic-debug", "obra/superpowers", "skills/systematic-debugging/SKILL.md")
get_skill("obra-root-cause", "obra/superpowers", "skills/root-cause-tracing/SKILL.md")
get_skill("obra-testing-subagents", "obra/superpowers", "skills/testing-skills-with-subagents/SKILL.md")
get_skill("obra-testing-antipatterns", "obra/superpowers", "skills/testing-anti-patterns/SKILL.md")
get_skill("obra-finish-branch", "obra/superpowers", "skills/finishing-a-development-branch/SKILL.md")
get_skill("obra-request-review", "obra/superpowers", "skills/requesting-code-review/SKILL.md")
get_skill("obra-receive-review", "obra/superpowers", "skills/receiving-code-review/SKILL.md")
get_skill("obra-git-worktrees", "obra/superpowers", "skills/using-git-worktrees/SKILL.md")
get_skill("obra-verification", "obra/superpowers", "skills/verification-before-completion/SKILL.md")
get_skill("obra-condition-waiting", "obra/superpowers", "skills/condition-based-waiting/SKILL.md")
get_skill("obra-writing-skills", "obra/superpowers", "skills/writing-skills/SKILL.md")
get_skill("obra-defense-in-depth", "obra/superpowers", "skills/defense-in-depth/SKILL.md")

print()
print("[ Context Engineering ]")
get_skill("ctx-fundamentals", "muratcankoylan/Agent-Skills-for-Context-Engineering", "skills/context-fundamentals/SKILL.md")
get_skill("ctx-degradation", "muratcankoylan/Agent-Skills-for-Context-Engineering", "skills/context-degradation/SKILL.md")
get_skill("ctx-compression", "muratcankoylan/Agent-Skills-for-Context-Engineering", "skills/context-compression/SKILL.md")
get_skill("ctx-optimization", "muratcankoylan/Agent-Skills-for-Context-Engineering", "skills/context-optimization/SKILL.md")
get_skill("ctx-multi-agent", "muratcankoylan/Agent-Skills-for-Context-Engineering", "skills/multi-agent-patterns/SKILL.md")
get_skill("ctx-memory-systems", "muratcankoylan/Agent-Skills-for-Context-Engineering", "skills/memory-systems/SKILL.md")
get_skill("ctx-tool-design", "muratcankoylan/Agent-Skills-for-Context-Engineering", "skills/tool-design/SKILL.md")
get_skill("ctx-evaluation", "muratcankoylan/Agent-Skills-for-Context-Engineering", "skills/evaluation/SKILL.md")

print()
print("[ Community: Development ]")
get_skill("community-terraform", "antonbabenko/terraform-skill", "SKILL.md")
get_skill("community-aws", "zxkane/aws-skills", "SKILL.md")
get_skill("community-rails-upgrade", "robzolkos/skill-rails-upgrade", "SKILL.md")
get_skill("community-ios-simulator", "conorluddy/ios-simulator-skill", "SKILL.md")
get_skill("community-playwright", "lackeyjb/playwright-skill", "SKILL.md")
get_skill("community-ui-skills", "ibelick/ui-skills", "SKILL.md")
get_skill("community-ui-ux-pro", "nextlevelbuilder/ui-ux-pro-max-skill", "SKILL.md")
get_skill("community-threejs", "CloudAI-X/threejs-skills", "SKILL.md")
get_skill("community-swiftui", "AvdLee/SwiftUI-Agent-Skill", "swiftui-expert-skill/SKILL.md")
get_skill("community-swift-patterns", "efremidze/swift-patterns-skill", "swift-patterns/SKILL.md")
get_skill("community-startup", "rameerez/claude-code-startup-skills", "SKILL.md")
get_skill("community-model-routing", "zscole/model-hierarchy-skill", "SKILL.md")
get_skill("community-deep-research", "sanjay3290/ai-skills", "skills/deep-research/SKILL.md")
get_skill("community-postgres", "sanjay3290/ai-skills", "skills/postgres/SKILL.md")
get_skill("community-recursive", "massimodeluisa/recursive-decomposition-skill", "SKILL.md")
get_skill("community-apple-hig", "raintree-technology/apple-hig-skills", "SKILL.md")
get_skill("community-security-blue", "SHADOWPR0/security-bluebook-builder", "SKILL.md")
get_skill("community-clickhouse", "ClickHouse/agent-skills", "SKILL.md")
get_skill("community-cloudflare-eng", "dmmulroy/cloudflare-skill", "skills/cloudflare/SKILL.md")
get_skill("community-seo", "AgriciDaniel/claude-seo", "SKILL.md")
get_skill("community-bootstrap", "alinaqi/claude-bootstrap", "SKILL.md")
get_skill("community-makepad", "ZhangHanDong/makepad-skills", "SKILL.md")
get_skill("community-ai-research", "zechenzhangAGI/AI-research-SKILLs", "SKILL.md")
get_skill("community-design-rules", "ehmo/platform-design-skills", "SKILL.md")
get_skill("community-swiftui-ios26", "AvdLee/SwiftUI-Agent-Skill", "swiftui-expert-skill/SKILL.md")
get_skill("community-swift-server", "Joannis/claude-skills", "SKILL.md")
get_skill("community-app-store", "rudrankriyam/app-store-connect-cli-skills", "SKILL.md")

print()
print("[ Community: n8n Automation ]")
get_skill("n8n-code-js", "czlonkowski/n8n-skills", "skills/n8n-code-javascript/SKILL.md")
get_skill("n8n-code-py", "czlonkowski/n8n-skills", "skills/n8n-code-python/SKILL.md")
get_skill("n8n-expr", "czlonkowski/n8n-skills", "skills/n8n-expression-syntax/SKILL.md")
get_skill("n8n-mcp", "czlonkowski/n8n-skills", "skills/n8n-mcp-tools-expert/SKILL.md")
get_skill("n8n-nodes", "czlonkowski/n8n-skills", "skills/n8n-node-configuration/SKILL.md")

print()
print("[ Community: Marketing ]")
get_skill("marketing-seo", "AgriciDaniel/claude-seo", "SKILL.md")
get_skill("marketing-email-bible", "CosmoBlk/email-marketing-bible", "SKILL.md")

print()
print("[ Community: Productivity ]")
get_skill("productivity-memory", "hanfang/claude-memory-skill", "SKILL.md")
get_skill("productivity-readme", "Shpigford/skills", "readme/SKILL.md")
get_skill("productivity-founder", "ognjengt/founder-skills", "SKILL.md")
get_skill("productivity-linear", "wrsmith108/linear-claude-skill", "SKILL.md")

print()
print("[ Microsoft - TypeScript ]")
get_skill("ms-frontend-dark", "microsoft/skills", ".github/skills/frontend-ui-dark-ts/SKILL.md")
get_skill("ms-react-flow", "microsoft/skills", ".github/skills/react-flow-node-ts/SKILL.md")
get_skill("ms-zustand", "microsoft/skills", ".github/skills/zustand-store-ts/SKILL.md")
get_skill("ms-azure-cosmos-ts", "microsoft/skills", ".github/skills/azure-cosmos-ts/SKILL.md")
get_skill("ms-azure-postgres-ts", "microsoft/skills", ".github/skills/azure-postgres-ts/SKILL.md")
get_skill("ms-azure-search-ts", "microsoft/skills", ".github/skills/azure-search-documents-ts/SKILL.md")
get_skill("ms-azure-identity-ts", "microsoft/skills", ".github/skills/azure-identity-ts/SKILL.md")
get_skill("ms-azure-storage-ts", "microsoft/skills", ".github/skills/azure-storage-blob-ts/SKILL.md")
get_skill("ms-azure-keyvault-ts", "microsoft/skills", ".github/skills/azure-keyvault-secrets-ts/SKILL.md")
get_skill("ms-azure-servicebus-ts", "microsoft/skills", ".github/skills/azure-servicebus-ts/SKILL.md")
get_skill("ms-azure-eventhub-ts", "microsoft/skills", ".github/skills/azure-eventhub-ts/SKILL.md")
get_skill("ms-azure-pubsub-ts", "microsoft/skills", ".github/skills/azure-web-pubsub-ts/SKILL.md")
get_skill("ms-azure-playwright-ts", "microsoft/skills", ".github/skills/azure-microsoft-playwright-testing-ts/SKILL.md")
get_skill("ms-azure-opentelemetry-ts", "microsoft/skills", ".github/skills/azure-monitor-opentelemetry-ts/SKILL.md")
get_skill("ms-azure-ai-projects-ts", "microsoft/skills", ".github/skills/azure-ai-projects-ts/SKILL.md")
get_skill("ms-azure-voicelive-ts", "microsoft/skills", ".github/skills/azure-ai-voicelive-ts/SKILL.md")
get_skill("ms-m365-agents-ts", "microsoft/skills", ".github/skills/m365-agents-ts/SKILL.md")

print()
print("[ Microsoft - Python ]")
get_skill("ms-fastapi-router", "microsoft/skills", ".github/skills/fastapi-router-py/SKILL.md")
get_skill("ms-pydantic-models", "microsoft/skills", ".github/skills/pydantic-models-py/SKILL.md")
get_skill("ms-azure-cosmos-py", "microsoft/skills", ".github/skills/azure-cosmos-py/SKILL.md")
get_skill("ms-azure-ai-ml", "microsoft/skills", ".github/skills/azure-ai-ml-py/SKILL.md")
get_skill("ms-azure-ai-projects-py", "microsoft/skills", ".github/skills/azure-ai-projects-py/SKILL.md")
get_skill("ms-azure-identity-py", "microsoft/skills", ".github/skills/azure-identity-py/SKILL.md")
get_skill("ms-azure-storage-py", "microsoft/skills", ".github/skills/azure-storage-blob-py/SKILL.md")
get_skill("ms-azure-keyvault-py", "microsoft/skills", ".github/skills/azure-keyvault-py/SKILL.md")
get_skill("ms-azure-search-py", "microsoft/skills", ".github/skills/azure-search-documents-py/SKILL.md")
get_skill("ms-azure-servicebus-py", "microsoft/skills", ".github/skills/azure-servicebus-py/SKILL.md")
get_skill("ms-azure-eventhub-py", "microsoft/skills", ".github/skills/azure-eventhub-py/SKILL.md")
get_skill("ms-azure-openai-py", "microsoft/skills", ".github/skills/azure-ai-contentunderstanding-py/SKILL.md")
get_skill("ms-azure-voicelive-py", "microsoft/skills", ".github/skills/azure-ai-voicelive-py/SKILL.md")
get_skill("ms-azure-speech-py", "microsoft/skills", ".github/skills/azure-ai-transcription-py/SKILL.md")
get_skill("ms-azure-translate-py", "microsoft/skills", ".github/skills/azure-ai-translation-text-py/SKILL.md")
get_skill("ms-m365-agents-py", "microsoft/skills", ".github/skills/m365-agents-py/SKILL.md")
get_skill("ms-agent-framework-py", "microsoft/skills", ".github/skills/agent-framework-azure-ai-py/SKILL.md")

print()
print("[ Microsoft - .NET ]")
get_skill("ms-azure-ai-agents-net", "microsoft/skills", ".github/skills/azure-ai-agents-persistent-dotnet/SKILL.md")
get_skill("ms-azure-openai-net", "microsoft/skills", ".github/skills/azure-ai-openai-dotnet/SKILL.md")
get_skill("ms-azure-cosmos-net", "microsoft/skills", ".github/skills/azure-resource-manager-cosmosdb-dotnet/SKILL.md")
get_skill("ms-azure-identity-net", "microsoft/skills", ".github/skills/azure-identity-dotnet/SKILL.md")
get_skill("ms-azure-storage-net", "microsoft/skills", ".github/skills/azure-storage-blob-dotnet/SKILL.md")
get_skill("ms-azure-keyvault-net", "microsoft/skills", ".github/skills/azure-security-keyvault-keys-dotnet/SKILL.md")
get_skill("ms-azure-search-net", "microsoft/skills", ".github/skills/azure-search-documents-dotnet/SKILL.md")
get_skill("ms-azure-servicebus-net", "microsoft/skills", ".github/skills/azure-servicebus-dotnet/SKILL.md")
get_skill("ms-azure-eventhub-net", "microsoft/skills", ".github/skills/azure-eventhub-dotnet/SKILL.md")
get_skill("ms-m365-agents-net", "microsoft/skills", ".github/skills/m365-agents-dotnet/SKILL.md")
get_skill("ms-azure-voicelive-net", "microsoft/skills", ".github/skills/azure-ai-voicelive-dotnet/SKILL.md")
get_skill("ms-mcp-builder-ms", "microsoft/skills", ".github/skills/mcp-builder/SKILL.md")
get_skill("ms-skill-creator-ms", "microsoft/skills", ".github/skills/skill-creator/SKILL.md")

print()
print("[ Microsoft - Java ]")
get_skill("ms-azure-cosmos-java", "microsoft/skills", ".github/skills/azure-cosmos-java/SKILL.md")
get_skill("ms-azure-identity-java", "microsoft/skills", ".github/skills/azure-identity-java/SKILL.md")
get_skill("ms-azure-eventhub-java", "microsoft/skills", ".github/skills/azure-eventhub-java/SKILL.md")
get_skill("ms-azure-ai-agents-java", "microsoft/skills", ".github/skills/azure-ai-agents-persistent-java/SKILL.md")
get_skill("ms-azure-voicelive-java", "microsoft/skills", ".github/skills/azure-ai-voicelive-java/SKILL.md")

print()
print("[ Microsoft - Rust ]")
get_skill("ms-azure-cosmos-rust", "microsoft/skills", ".github/skills/azure-cosmos-rust/SKILL.md")
get_skill("ms-azure-identity-rust", "microsoft/skills", ".github/skills/azure-identity-rust/SKILL.md")
get_skill("ms-azure-keyvault-rust", "microsoft/skills", ".github/skills/azure-keyvault-secrets-rust/SKILL.md")
get_skill("ms-azure-storage-rust", "microsoft/skills", ".github/skills/azure-storage-blob-rust/SKILL.md")

print()
print("================================================================")
print(f"  Done: {OK} fetched, {FAIL} failed")
total = len(list(SKILLS_DIR.glob("*.md")))
print(f"  Total .md files in skills/: {total}")
print("================================================================")
print()

