/**
 * Budget Service
 * Full budget lifecycle management with automated generation from historical data
 * and budget-vs-actual variance analysis.
 */

import { db, budgets, budgetLines, budgetVsActual, transactions } from '../schema.js';
import { eq, and, gte, lte, sql } from 'drizzle-orm';
import crypto from 'crypto';

// ============================================================================
// TYPE DEFINITIONS
// ============================================================================

export interface CreateBudgetParams {
  name: string;
  budgetType: 'annual' | 'quarterly' | 'monthly' | 'project';
  periodStart: string;
  periodEnd: string;
  accountId?: string;
  autoGenerate?: boolean;
  lookbackMonths?: number;
}

export interface CreateBudgetLineParams {
  category: string;
  subcategory?: string;
  period: string;
  budgetedAmount: number;
  notes?: string;
}

export interface VarianceSummary {
  totalBudgeted: number;
  totalActual: number;
  totalVariance: number;
  overBudgetCategories: Array<{ category: string; variance: number; percent: number }>;
  underBudgetCategories: Array<{ category: string; variance: number; percent: number }>;
  topVariances: Array<{ category: string; budgeted: number; actual: number; variance: number }>;
  health: 'on_track' | 'over_budget' | 'under_budget';
}

// ============================================================================
// BUDGET SERVICE
// ============================================================================

export class BudgetService {
  // --------------------------------------------------------------------------
  // CRUD Operations
  // --------------------------------------------------------------------------

  async createBudget(userId: string, params: CreateBudgetParams) {
    const now = new Date().toISOString();
    const budgetId = crypto.randomUUID();

    const newBudget = {
      id: budgetId,
      userId,
      name: params.name,
      budgetType: params.budgetType,
      periodStart: params.periodStart,
      periodEnd: params.periodEnd,
      accountId: params.accountId ?? null,
      totalAmount: 0,
      status: 'draft',
      autoGenerated: params.autoGenerate ?? false,
      sourceMethod: params.autoGenerate ? 'historical_average' : 'manual',
      createdAt: now,
      updatedAt: now,
    };

    await db.insert(budgets).values(newBudget);

    let lines: any[] = [];
    if (params.autoGenerate) {
      const lookback = params.lookbackMonths ?? 12;
      lines = await this.generateFromHistory(userId, params.periodStart, params.periodEnd, lookback, budgetId);

      // Update total from generated lines
      const total = lines.reduce((sum: number, l: any) => sum + Math.abs(l.budgetedAmount), 0);
      await db
        .update(budgets)
        .set({ totalAmount: total, updatedAt: new Date().toISOString() })
        .where(eq(budgets.id, budgetId));
    }

    return { ...newBudget, lines };
  }

  async getBudget(budgetId: string) {
    const budget = await db
      .select()
      .from(budgets)
      .where(eq(budgets.id, budgetId))
      .get();

    if (!budget) return null;

    const lines = await db
      .select()
      .from(budgetLines)
      .where(eq(budgetLines.budgetId, budgetId))
      .all();

    // Calculate totals per category
    const categoryTotals = new Map<string, number>();
    for (const line of lines) {
      const current = categoryTotals.get(line.category) ?? 0;
      categoryTotals.set(line.category, current + line.budgetedAmount);
    }

    return {
      ...budget,
      lines,
      categoryTotals: Object.fromEntries(categoryTotals),
    };
  }

  async listBudgets(userId: string, status?: string) {
    if (status) {
      return db
        .select()
        .from(budgets)
        .where(and(eq(budgets.userId, userId), eq(budgets.status, status)))
        .orderBy(sql`${budgets.periodStart} DESC`)
        .all();
    }

    return db
      .select()
      .from(budgets)
      .where(eq(budgets.userId, userId))
      .orderBy(sql`${budgets.periodStart} DESC`)
      .all();
  }

  async updateBudget(budgetId: string, updates: Partial<{ name: string; status: string; periodStart: string; periodEnd: string }>) {
    const now = new Date().toISOString();

    await db
      .update(budgets)
      .set({ ...updates, updatedAt: now })
      .where(eq(budgets.id, budgetId));

    // Recalculate total from budget lines
    const lines = await db
      .select()
      .from(budgetLines)
      .where(eq(budgetLines.budgetId, budgetId))
      .all();

    const total = lines.reduce((sum: number, l: any) => sum + Math.abs(l.budgetedAmount), 0);
    await db
      .update(budgets)
      .set({ totalAmount: total })
      .where(eq(budgets.id, budgetId));

    return this.getBudget(budgetId);
  }

  async deleteBudget(budgetId: string): Promise<void> {
    // CASCADE delete handles budget_lines and budget_vs_actual
    await db.delete(budgets).where(eq(budgets.id, budgetId));
  }

  // --------------------------------------------------------------------------
  // Budget Line Operations
  // --------------------------------------------------------------------------

  async addBudgetLine(budgetId: string, line: CreateBudgetLineParams) {
    const lineId = crypto.randomUUID();
    const now = new Date().toISOString();

    const newLine = {
      id: lineId,
      budgetId,
      category: line.category,
      subcategory: line.subcategory ?? null,
      period: line.period,
      budgetedAmount: line.budgetedAmount,
      notes: line.notes ?? null,
      createdAt: now,
    };

    await db.insert(budgetLines).values(newLine);

    // Recalculate parent budget total
    await this.recalculateBudgetTotal(budgetId);

    return newLine;
  }

  async updateBudgetLine(lineId: string, updates: Partial<{ budgetedAmount: number; notes: string }>) {
    await db
      .update(budgetLines)
      .set(updates)
      .where(eq(budgetLines.id, lineId));

    // Get line to find parent budget
    const line = await db
      .select()
      .from(budgetLines)
      .where(eq(budgetLines.id, lineId))
      .get();

    if (line) {
      await this.recalculateBudgetTotal(line.budgetId);
    }

    return db.select().from(budgetLines).where(eq(budgetLines.id, lineId)).get();
  }

  async deleteBudgetLine(lineId: string): Promise<void> {
    // Get line to find parent budget before deleting
    const line = await db
      .select()
      .from(budgetLines)
      .where(eq(budgetLines.id, lineId))
      .get();

    await db.delete(budgetLines).where(eq(budgetLines.id, lineId));

    if (line) {
      await this.recalculateBudgetTotal(line.budgetId);
    }
  }

  // --------------------------------------------------------------------------
  // Auto-Generation from Historical Data
  // --------------------------------------------------------------------------

  async generateFromHistory(
    userId: string,
    periodStart: string,
    periodEnd: string,
    lookbackMonths: number,
    budgetId?: string
  ) {
    // Calculate lookback window
    const startDate = new Date(periodStart);
    const lookbackStart = new Date(startDate);
    lookbackStart.setMonth(lookbackStart.getMonth() - lookbackMonths);
    const lookbackStartStr = lookbackStart.toISOString().split('T')[0];
    const lookbackEndStr = startDate.toISOString().split('T')[0];

    // Query historical transactions grouped by category and month
    const historicalData = await db
      .select({
        category: transactions.category,
        month: sql<string>`SUBSTR(${transactions.date}, 1, 7)`,
        totalAmount: sql<number>`SUM(ABS(${transactions.amount}))`,
        txCount: sql<number>`COUNT(*)`,
      })
      .from(transactions)
      .where(
        and(
          eq(transactions.userId, userId),
          gte(transactions.date, lookbackStartStr),
          lte(transactions.date, lookbackEndStr),
          sql`${transactions.category} IS NOT NULL`
        )
      )
      .groupBy(transactions.category, sql`SUBSTR(${transactions.date}, 1, 7)`)
      .all();

    // Build category → month → amount map
    const categoryMonthMap = new Map<string, Map<string, number>>();
    for (const row of historicalData) {
      const cat = row.category as string;
      if (!categoryMonthMap.has(cat)) {
        categoryMonthMap.set(cat, new Map());
      }
      categoryMonthMap.get(cat)!.set(row.month, Number(row.totalAmount));
    }

    // Calculate averages and seasonal factors per category
    const generatedLines: any[] = [];
    const targetMonths = getMonthsBetween(periodStart, periodEnd);

    for (const [category, monthAmounts] of categoryMonthMap) {
      const amounts = Array.from(monthAmounts.values());
      const overallAvg = amounts.reduce((s, v) => s + v, 0) / amounts.length;

      // Seasonal factors: ratio of each calendar month's average to overall average
      const monthFactors = new Map<number, number>();
      const monthSums = new Map<number, { total: number; count: number }>();

      for (const [monthStr, amount] of monthAmounts) {
        const calMonth = parseInt(monthStr.split('-')[1]);
        const existing = monthSums.get(calMonth) ?? { total: 0, count: 0 };
        monthSums.set(calMonth, { total: existing.total + amount, count: existing.count + 1 });
      }

      for (const [calMonth, data] of monthSums) {
        const monthAvg = data.total / data.count;
        monthFactors.set(calMonth, overallAvg > 0 ? monthAvg / overallAvg : 1.0);
      }

      // Generate budget lines for each target month
      for (const targetMonth of targetMonths) {
        const calMonth = parseInt(targetMonth.split('-')[1]);
        const seasonalFactor = monthFactors.get(calMonth) ?? 1.0;
        const budgetedAmount = Math.round(overallAvg * seasonalFactor);

        const lineData: any = {
          id: crypto.randomUUID(),
          category,
          subcategory: null,
          period: targetMonth,
          budgetedAmount,
          notes: `Auto-generated from ${lookbackMonths}mo history (seasonal factor: ${seasonalFactor.toFixed(2)})`,
          createdAt: new Date().toISOString(),
        };

        if (budgetId) {
          lineData.budgetId = budgetId;
          await db.insert(budgetLines).values(lineData);
        }

        generatedLines.push(lineData);
      }
    }

    return generatedLines;
  }

  // --------------------------------------------------------------------------
  // Budget vs Actual
  // --------------------------------------------------------------------------

  async calculateVariance(budgetId: string) {
    const budget = await db.select().from(budgets).where(eq(budgets.id, budgetId)).get();
    if (!budget) throw new Error(`Budget not found: ${budgetId}`);

    const lines = await db.select().from(budgetLines).where(eq(budgetLines.budgetId, budgetId)).all();
    const results: any[] = [];

    for (const line of lines) {
      // Determine date range for this budget line's period
      const { startDate, endDate } = getPeriodDateRange(line.period);

      // Query actual transactions matching category + period
      const actualResult = await db
        .select({
          totalAmount: sql<number>`COALESCE(SUM(ABS(${transactions.amount})), 0)`,
          txCount: sql<number>`COUNT(*)`,
        })
        .from(transactions)
        .where(
          and(
            eq(transactions.userId, budget.userId),
            eq(transactions.category, line.category),
            gte(transactions.date, startDate),
            lte(transactions.date, endDate)
          )
        )
        .get();

      const actualAmount = Number(actualResult?.totalAmount ?? 0);
      const varianceAmount = actualAmount - line.budgetedAmount;
      const variancePercent = line.budgetedAmount !== 0
        ? (varianceAmount / Math.abs(line.budgetedAmount)) * 100
        : 0;

      const now = new Date().toISOString();

      // Check for existing budget_vs_actual row for this line
      const existing = await db
        .select()
        .from(budgetVsActual)
        .where(eq(budgetVsActual.budgetLineId, line.id))
        .get();

      const record = {
        actualAmount,
        varianceAmount,
        variancePercent,
        transactionCount: Number(actualResult?.txCount ?? 0),
        lastCalculated: now,
      };

      if (existing) {
        await db
          .update(budgetVsActual)
          .set(record)
          .where(eq(budgetVsActual.id, existing.id));
        results.push({ ...existing, ...record, budgetLine: line });
      } else {
        const newRecord = {
          id: crypto.randomUUID(),
          budgetLineId: line.id,
          ...record,
        };
        await db.insert(budgetVsActual).values(newRecord);
        results.push({ ...newRecord, budgetLine: line });
      }
    }

    return results;
  }

  async getVarianceSummary(budgetId: string): Promise<VarianceSummary> {
    // Ensure variance is calculated
    const varianceRows = await this.calculateVariance(budgetId);

    let totalBudgeted = 0;
    let totalActual = 0;
    const categoryVariances: Array<{ category: string; budgeted: number; actual: number; variance: number; percent: number }> = [];

    // Aggregate by category
    const categoryMap = new Map<string, { budgeted: number; actual: number }>();

    for (const row of varianceRows) {
      const cat = row.budgetLine.category;
      const existing = categoryMap.get(cat) ?? { budgeted: 0, actual: 0 };
      categoryMap.set(cat, {
        budgeted: existing.budgeted + row.budgetLine.budgetedAmount,
        actual: existing.actual + row.actualAmount,
      });
    }

    for (const [category, data] of categoryMap) {
      const variance = data.actual - data.budgeted;
      const percent = data.budgeted !== 0 ? (variance / Math.abs(data.budgeted)) * 100 : 0;
      totalBudgeted += data.budgeted;
      totalActual += data.actual;
      categoryVariances.push({ category, budgeted: data.budgeted, actual: data.actual, variance, percent });
    }

    const totalVariance = totalActual - totalBudgeted;

    // Classify categories
    const overBudgetCategories = categoryVariances
      .filter(c => c.variance > 0)
      .map(c => ({ category: c.category, variance: c.variance, percent: c.percent }))
      .sort((a, b) => b.variance - a.variance);

    const underBudgetCategories = categoryVariances
      .filter(c => c.variance < 0)
      .map(c => ({ category: c.category, variance: c.variance, percent: c.percent }))
      .sort((a, b) => a.variance - b.variance);

    // Top 5 largest absolute variances
    const topVariances = [...categoryVariances]
      .sort((a, b) => Math.abs(b.variance) - Math.abs(a.variance))
      .slice(0, 5)
      .map(c => ({ category: c.category, budgeted: c.budgeted, actual: c.actual, variance: c.variance }));

    // Health: on_track if |totalVariance| < 10% of totalBudgeted
    let health: 'on_track' | 'over_budget' | 'under_budget';
    if (totalBudgeted === 0) {
      health = 'on_track';
    } else if (Math.abs(totalVariance) < Math.abs(totalBudgeted) * 0.10) {
      health = 'on_track';
    } else if (totalActual > totalBudgeted) {
      health = 'over_budget';
    } else {
      health = 'under_budget';
    }

    return {
      totalBudgeted,
      totalActual,
      totalVariance,
      overBudgetCategories,
      underBudgetCategories,
      topVariances,
      health,
    };
  }

  // --------------------------------------------------------------------------
  // Private Helpers
  // --------------------------------------------------------------------------

  private async recalculateBudgetTotal(budgetId: string) {
    const lines = await db
      .select()
      .from(budgetLines)
      .where(eq(budgetLines.budgetId, budgetId))
      .all();

    const total = lines.reduce((sum: number, l: any) => sum + Math.abs(l.budgetedAmount), 0);

    await db
      .update(budgets)
      .set({ totalAmount: total, updatedAt: new Date().toISOString() })
      .where(eq(budgets.id, budgetId));
  }
}

// ============================================================================
// UTILITY FUNCTIONS
// ============================================================================

/** Get array of YYYY-MM strings between two dates */
function getMonthsBetween(startStr: string, endStr: string): string[] {
  const months: string[] = [];
  const start = new Date(startStr);
  const end = new Date(endStr);

  const current = new Date(start.getFullYear(), start.getMonth(), 1);
  const endMonth = new Date(end.getFullYear(), end.getMonth(), 1);

  while (current <= endMonth) {
    const year = current.getFullYear();
    const month = String(current.getMonth() + 1).padStart(2, '0');
    months.push(`${year}-${month}`);
    current.setMonth(current.getMonth() + 1);
  }

  return months;
}

/** Convert a period string (YYYY-MM or YYYY-QN) to a date range */
function getPeriodDateRange(period: string): { startDate: string; endDate: string } {
  if (period.includes('Q')) {
    // Quarterly: 2025-Q1 → Jan-Mar
    const [yearStr, qStr] = period.split('-Q');
    const year = parseInt(yearStr);
    const quarter = parseInt(qStr);
    const startMonth = (quarter - 1) * 3;
    const start = new Date(year, startMonth, 1);
    const end = new Date(year, startMonth + 3, 0); // last day of quarter
    return {
      startDate: start.toISOString().split('T')[0],
      endDate: end.toISOString().split('T')[0],
    };
  }

  // Monthly: 2025-01 → full month
  const [yearStr, monthStr] = period.split('-');
  const year = parseInt(yearStr);
  const month = parseInt(monthStr) - 1;
  const start = new Date(year, month, 1);
  const end = new Date(year, month + 1, 0); // last day of month
  return {
    startDate: start.toISOString().split('T')[0],
    endDate: end.toISOString().split('T')[0],
  };
}

export const budgetService = new BudgetService();
