import { sqliteTable, text, integer, real } from 'drizzle-orm/sqlite-core';
import { users } from './core.js';
import { accounts, statements } from './banking.js';
import { transactions } from './transactions.js';

// ============================================================================
// PARSER METRICS & FEEDBACK
// ============================================================================

export const parserMetrics = sqliteTable('parser_metrics', {
  id: text('id').primaryKey(),
  statementId: text('statement_id').references(() => statements.id, { onDelete: 'cascade' }),
  bankName: text('bank_name').notNull(),
  parserUsed: text('parser_used').notNull(),
  extractionTimeMs: integer('extraction_time_ms'),
  transactionCount: integer('transaction_count'),
  confidenceScore: real('confidence_score'),
  errorsCount: integer('errors_count').default(0),
  warningsCount: integer('warnings_count').default(0),
  usedVisionFallback: integer('used_vision_fallback', { mode: 'boolean' }).default(false),
  bankId: text('bank_id'),
  totalDurationMs: integer('total_duration_ms'),
  parseErrorCount: integer('parse_error_count'),
  transactionsParsed: integer('transactions_parsed'),
  detectionConfidence: real('detection_confidence'),
  highConfidenceCount: integer('high_confidence_count'),
  lowConfidenceCount: integer('low_confidence_count'),
  extractionMethod: text('extraction_method'),
  createdAt: text('created_at').notNull().default('CURRENT_TIMESTAMP'),
});

export const parserAccuracyAggregates = sqliteTable('parser_accuracy_aggregates', {
  id: text('id').primaryKey(),
  bankName: text('bank_name').notNull(),
  parserVersion: text('parser_version').notNull(),
  periodStart: text('period_start').notNull(),
  periodEnd: text('period_end').notNull(),
  totalStatements: integer('total_statements').notNull().default(0),
  successfulStatements: integer('successful_statements').notNull().default(0),
  avgConfidenceScore: real('avg_confidence_score'),
  avgExtractionTimeMs: real('avg_extraction_time_ms'),
  visionFallbackRate: real('vision_fallback_rate'),
  bankId: text('bank_id'),
  periodType: text('period_type'),
  createdAt: text('created_at').notNull().default('CURRENT_TIMESTAMP'),
});

export const parserFeedback = sqliteTable('parser_feedback', {
  id: text('id').primaryKey(),
  userId: text('user_id')
    .notNull()
    .references(() => users.id, { onDelete: 'cascade' }),
  statementId: text('statement_id').references(() => statements.id, { onDelete: 'set null' }),
  transactionId: text('transaction_id').references(() => transactions.id, { onDelete: 'set null' }),
  feedbackType: text('feedback_type').notNull(),
  originalValue: text('original_value'),
  correctedValue: text('corrected_value'),
  fieldName: text('field_name'),
  notes: text('notes'),
  aiConfidence: text('ai_confidence'),
  userNotes: text('user_notes'),
  status: text('status').notNull().default('pending'),
  bankId: text('bank_id'),
  reviewedAt: text('reviewed_at'),
  reviewNotes: text('review_notes'),
  createdAt: text('created_at').notNull().default('CURRENT_TIMESTAMP'),
});

// ============================================================================
// FINANCIAL REPORTING & BUDGETING (Wave 13)
// ============================================================================

export const reportSnapshots = sqliteTable('report_snapshots', {
  id: text('id').primaryKey(),
  templateId: text('template_id').notNull(),
  userId: text('user_id')
    .notNull()
    .references(() => users.id, { onDelete: 'cascade' }),
  reportType: text('report_type').notNull(),
  periodStart: text('period_start').notNull(),
  periodEnd: text('period_end').notNull(),
  data: text('data').notNull(),
  comparisonData: text('comparison_data'),
  metadata: text('metadata'),
  generatedAt: text('generated_at').notNull().default('CURRENT_TIMESTAMP'),
});

export const budgets = sqliteTable('budgets', {
  id: text('id').primaryKey(),
  userId: text('user_id')
    .notNull()
    .references(() => users.id, { onDelete: 'cascade' }),
  accountId: text('account_id').references(() => accounts.id, { onDelete: 'set null' }),
  name: text('name').notNull(),
  budgetType: text('budget_type').notNull(),
  periodStart: text('period_start').notNull(),
  periodEnd: text('period_end').notNull(),
  totalAmount: real('total_amount').notNull().default(0),
  status: text('status').notNull().default('draft'),
  autoGenerated: integer('auto_generated', { mode: 'boolean' }).default(false),
  sourceMethod: text('source_method'),
  createdAt: text('created_at').notNull().default('CURRENT_TIMESTAMP'),
  updatedAt: text('updated_at').notNull().default('CURRENT_TIMESTAMP'),
});

export const budgetLines = sqliteTable('budget_lines', {
  id: text('id').primaryKey(),
  budgetId: text('budget_id')
    .notNull()
    .references(() => budgets.id, { onDelete: 'cascade' }),
  category: text('category').notNull(),
  subcategory: text('subcategory'),
  period: text('period').notNull(),
  budgetedAmount: real('budgeted_amount').notNull(),
  notes: text('notes'),
  createdAt: text('created_at').notNull().default('CURRENT_TIMESTAMP'),
});

export const budgetVsActual = sqliteTable('budget_vs_actual', {
  id: text('id').primaryKey(),
  budgetLineId: text('budget_line_id')
    .notNull()
    .references(() => budgetLines.id, { onDelete: 'cascade' }),
  actualAmount: real('actual_amount').notNull().default(0),
  varianceAmount: real('variance_amount').notNull().default(0),
  variancePercent: real('variance_percent').default(0),
  transactionCount: integer('transaction_count').default(0),
  lastCalculated: text('last_calculated').notNull().default('CURRENT_TIMESTAMP'),
});

export const forecastScenarios = sqliteTable('forecast_scenarios', {
  id: text('id').primaryKey(),
  userId: text('user_id')
    .notNull()
    .references(() => users.id, { onDelete: 'cascade' }),
  name: text('name').notNull(),
  scenarioType: text('scenario_type').notNull(),
  basePeriodStart: text('base_period_start').notNull(),
  basePeriodEnd: text('base_period_end').notNull(),
  forecastMonths: integer('forecast_months').notNull().default(12),
  assumptions: text('assumptions').notNull(),
  status: text('status').default('draft'),
  createdAt: text('created_at').notNull().default('CURRENT_TIMESTAMP'),
  updatedAt: text('updated_at').notNull().default('CURRENT_TIMESTAMP'),
});

export const forecastPeriods = sqliteTable('forecast_periods', {
  id: text('id').primaryKey(),
  scenarioId: text('scenario_id')
    .notNull()
    .references(() => forecastScenarios.id, { onDelete: 'cascade' }),
  period: text('period').notNull(),
  category: text('category').notNull(),
  forecastAmount: real('forecast_amount').notNull(),
  confidenceLower: real('confidence_lower'),
  confidenceUpper: real('confidence_upper'),
  method: text('method').notNull(),
});

export const kpiMetrics = sqliteTable('kpi_metrics', {
  id: text('id').primaryKey(),
  userId: text('user_id')
    .notNull()
    .references(() => users.id, { onDelete: 'cascade' }),
  metricName: text('metric_name').notNull(),
  metricValue: real('metric_value').notNull(),
  period: text('period').notNull(),
  targetValue: real('target_value'),
  trendDirection: text('trend_direction'),
  previousValue: real('previous_value'),
  calculatedAt: text('calculated_at').notNull().default('CURRENT_TIMESTAMP'),
});

// Type exports
export type ParserMetric = typeof parserMetrics.$inferSelect;
export type ParserAccuracyAggregate = typeof parserAccuracyAggregates.$inferSelect;
export type ParserFeedbackRecord = typeof parserFeedback.$inferSelect;
