import type { FeedbackItem } from './types.js';

export const mockFeedback: FeedbackItem[] = [
  {
    id: 'f1',
    userId: 'u1',
    username: 'john.doe',
    transactionId: 't1',
    transactionDescription: 'WOOLWORTHS 1234 SYDNEY',
    transactionAmount: -8750,
    feedbackType: 'category_correction',
    originalValue: 'Shopping',
    suggestedValue: 'Groceries',
    userComment: 'This should be Groceries, not general Shopping',
    status: 'pending',
    createdAt: '2024-01-28T10:30:00Z',
  },
  {
    id: 'f2',
    userId: 'u2',
    username: 'jane.smith',
    transactionId: 't2',
    transactionDescription: 'OFFICE SUPPLIES CO',
    transactionAmount: -24500,
    feedbackType: 'gst_correction',
    originalValue: 'No GST',
    suggestedValue: 'GST Applicable',
    userComment: 'Office supplies include GST',
    status: 'pending',
    createdAt: '2024-01-28T09:15:00Z',
  },
  {
    id: 'f3',
    userId: 'u1',
    username: 'john.doe',
    transactionId: 't3',
    transactionDescription: 'UBER *EATS SYDNEY AU',
    transactionAmount: -3250,
    feedbackType: 'category_correction',
    originalValue: 'Transport',
    suggestedValue: 'Food & Dining',
    status: 'approved',
    createdAt: '2024-01-27T16:45:00Z',
    reviewedAt: '2024-01-27T18:00:00Z',
    reviewedBy: 'admin',
  },
  {
    id: 'f4',
    userId: 'u3',
    username: 'bob.wilson',
    transactionId: 't4',
    transactionDescription: 'INTEREST CHARGE',
    transactionAmount: -1523,
    feedbackType: 'parser_error',
    originalValue: 'Parsed as income',
    suggestedValue: 'Should be expense',
    userComment: 'Parser incorrectly identified this as income',
    status: 'pending',
    createdAt: '2024-01-28T08:00:00Z',
  },
  {
    id: 'f5',
    userId: 'u2',
    username: 'jane.smith',
    transactionId: 't5',
    transactionDescription: 'AMAZON AU MARKETPLACE',
    transactionAmount: -15999,
    feedbackType: 'category_correction',
    originalValue: 'Shopping',
    suggestedValue: 'Business Expense',
    userComment: 'This was a business purchase',
    status: 'rejected',
    createdAt: '2024-01-26T14:20:00Z',
    reviewedAt: '2024-01-27T10:00:00Z',
    reviewedBy: 'admin',
  },
];
